baseURL = "https://claudiovargas1988.github.io"
title = "Claudio Vargas"
theme = "educenter-hugo"
publishDir = "docs"
tags = ["blog",'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'business', 'education', 'white', 'light', 'multilingual', "bootstrap", "company", "portfolio", "projects", "responsive", "themefisher"]
features = ["blog", "company", "responsive", "seo-esiendly"]

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Tuviste un accidente de tránsito? no te preocupes contactame que yo puedo ayudarte USA Miami"
author = "Claudio Vargas"
# contact info
address = "United States (Estados Unidos)"
mobile = "+1 (786) 731-1852"
email = "contacto@claudiovargas305.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true
navbar = false

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/claudio.vargas.75098364"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/claudiok1"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/claudiovargas1988"

[[params.social]]
title = "whatsap"
icon = "ti-comments-smiley" # themify icon : https://themify.me/themify-icons
link = "https://api.whatsapp.com/send?phone=17867311852&text=Hola Claudio!%20Quiero%20hacerte%20una%20consulta%20saludos!"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/claudiovargas1"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "Inicio"
url = ""
weight = 1

#[[Languages.en.menu.main]]
#name = "course"
#url = "course"
#weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "scholarship"
  url = "scholarship"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research"
  
#[[Languages.en.menu.main]]
#name = "blog"
#url = "blog"
#weight = 4
  
[[Languages.en.menu.main]]
name = "Contacto"
url = "contact"
weight = 5


# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice"

[[Languages.en.menu.footer]]
name = "event"
url = "event"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.footer]]
name = "research"
url = "research"



################################### Spanish language #####################################
[Languages.es]
languageName = "es"
languageCode = "es-es"
contentDir = "content/esench"
weight = 2
home = "Inicio"
# copyright
copyright = "Copyright &copy; 2020"



################### Spanish navigation ####################

# main menu
[[Languages.es.menu.main]]
name = "Acerca"
url = "about"
weight = 1

[[Languages.es.menu.main]]
name = "Cursos"
url = "course"
weight = 2

[[Languages.es.menu.main]]
weight = 3
name = "Paguinas"
hasChildren = true

  [[Languages.es.menu.main]]
  parent = "Pages"
  name = "maestro"
  url = "teacher"

  [[Languages.es.menu.main]]
  parent = "Pages"
  name = "noticias"
  url = "notice"

  [[Languages.es.menu.main]]
  parent = "Pages"
  name = "eventos"
  url = "event"

  [[Languages.es.menu.main]]
  parent = "Pages"
  name = "becas"
  url = "scholarship"

  [[Languages.es.menu.main]]
  parent = "Pages"
  name = "investigaciòn"
  url = "research"
  
[[Languages.es.menu.main]]
name = "blog"
url = "blog"
weight = 4
  
[[Languages.es.menu.main]]
name = "contacto"
url = "contact"
weight = 5


# footer menu

[[Languages.es.menu.footer]]
name = "maestro"
url = "teacher"

[[Languages.es.menu.footer]]
name = "noticias"
url = "notice"

[[Languages.es.menu.footer]]
name = "eventos"
url = "event"

[[Languages.es.menu.footer]]
name = "Becas"
url = "scholarship"

[[Languages.es.menu.footer]]
name = "investigaciòn"
url = "research"
